src/Entity/DateFr.php
<?php

namespace App\Entity;

use DateTime;
use Doctrine\ORM\Mapping as ORM;

/**
 * Entité pour la date en français.
 * Class DateFr
 * @package App\Entity
 */
class DateFr
{
    /**
     * @var DateTime
     */
    private $datetime;

    /**
     * @var array
     */
    private $mois = [
        1 => "janvier",
        2 => "février",
        3 => "mars",
        4 => "avril",
        5 => "mai",
        6 => "juin",
        7 => "juillet",
        8 => "août",
        9 => "septembre",
        10 => "octobre",
        11 => "novembre",
        12 => "décembre"
    ];

    /**
     * @var array
     */
    private $semaines = [
        1 => "lundi",
        2 => "mardi",
        3 => "mercredi",
        4 => "jeudi",
        5 => "vendredi",
        6 => "samedi",
        7 => "dimanche"
    ];

    /**
     * DateFr constructor.
     * @param DateTime $dateTime
     */
    public function __construct(DateTime $dateTime)
    {
        $this->datetime = $dateTime;
    }


    /**
     * @return DateTime
     */
    public function getDatetime(): DateTime
    {
        return $this->datetime;
    }

    /**
     * @param DateTime $datetime
     */
    public function setDatetime(DateTime $datetime): void
    {
        $this->datetime = $datetime;
    }

    /**
     * @return string
     */
    public function getAnnee()
    {
        return $this->datetime->format("Y");
    }

    /**
     * @return string
     */
    public function getAnneeNumerique()
    {
        return $this->datetime->format("y");
    }

    /**
     * @return mixed
     */
    public function getMois()
    {
        $index = $this->datetime->format("n");
        $index = intval($index);

        return $this->mois[$index];
    }

    /**
     * @return string
     */
    public function getMoisNumerique()
    {
        return $this->datetime->format("m");
    }

    /**
     * @return mixed
     */
    public function getSemaine()
    {
        $index = $this->datetime->format("N");
        $index = intval($index);

        return $this->semaines[$index];
    }

    /**
     * @return string
     */
    public function getJour()
    {
        return $this->datetime->format("j");
    }

    public function getHeure(){

        return $this->datetime->format("H");
    }

    public function getMinute(){

        return $this->datetime->format("i");
    }

    public function getSeconde(){

        return $this->datetime->format("s");
    }

    public function getTemps(){

        return $this->getHeure() . "h" . $this->getMinute();
    }


    /**
     * @return string
     */
    public function __toString(): ?string
    {
        return
            $this->getJour() . " " .
            $this->getMois() . " " .
            $this->getAnnee()
            ;
    }
}

templates/app/categorie.html.twig
{% extends 'base.html.twig' %}

{#
    # Author : PORTET Marin
    # Description : This page is a list of products for one categorie
#}

{% block title %}Catégorie{% endblock %}

{% block body %}
    <div class="pt-5">

        <div class="container-fluid">

            {# Main Title #}
            <h1 class="h1 font-weight-bold">Catégorie {{ categorie.nom | title }}</h1>

            {# Separator #}
            <hr class="my-5">


            {# List Of Products For One Categorie #}
            <div id="cat{{ categorie.id }}" class="container">

                {# List Of Products #}
                <div class="row row-cols-1 row-cols-md-2 row-cols-lg-3">
                    {% for produit in categorie.produits %}
                        <div class="col mb-4">
                            <div class="card h-100">
                                {% for image in produit.images %}
                                    <img src="{{ image }}" class="card-img-top" alt="{{ image.alternative }}">
                                {% endfor %}
                                <div class="card-body">
                                    <h3 class="card-title">{{ produit.nom | title }}</h3>
                                    <p class="card-text">{{ produit.description }}</p>
                                    <a class="card-link btn btn-primary " href="{{ path("app_product", {"categorie" : categorie.nom, "id" : produit.id} ) }}">En savoir plus...</a>
                                </div>
                                <div class="card-footer">
                                    <p class="card-text text-muted text-right"> Ajouter le : {{ produit.dateFr }} </p>
                                </div>
                            </div>
                        </div>

                    {% endfor %}
                </div>

                {# Button to back in the list for all products #}
                <div class="row justify-content-end">
                    <a class="col-3 btn btn-primary btn-lg" href="{{ path("app_categories") }}">Retour</a>
                </div>
            </div>

            {# Separator #}
            <hr class="my-5">

        </div>


    </div>
{% endblock %}

templates/app/categories.html.twig
{% extends 'base.html.twig' %}

{#
    # Author : PORTET Marin
    # Description : This page is a list for all products
#}

{% block title %}Catégories{% endblock %}

{% block body %}
    <div class="pt-5">

        <div class="container-fluid">

            {# Main Title #}
            <h1 class="h1 font-weight-bold">Catégories</h1>

            {# Separator #}
            <hr class="my-3">



            {# Options Catégories #}
            <div class="container">
                <h2>Options :</h2>
                <div class="container">
                    <div class="dropdown">
                        <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Select
                        </button>
                        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                            {% for categorie in categories %}

                                <a class="dropdown-item" href="#cat{{ categorie.id }}" aria-pressed="true">Catégorie {{ categorie.nom | title }}</a>

                            {% endfor %}
                        </div>
                    </div>
                </div>
            </div>

            {# Separator #}
            <hr class="my-5">


            {# List of Products By Categorie #}
            {% for categorie in categories %}
                <div id="cat{{ categorie.id }}" class="container">

                    {# Title of categorie #}
                    <div class="row mt-5 mb-3">
                        <h2 class="h2 col-auto"> Catégorie {{ categorie.nom | title }}</h2>
                    </div>

                    {# List of Products #}
                    <div class="row row-cols-1 row-cols-md-2 row-cols-lg-3">
                        {% for produit in categorie.produits %}
                            {% if loop.index <= 5 %}
                                <div class="col mb-4">
                                    <div class="card h-100">
                                        {% for image in produit.images %}
                                            <img src="{{ image }}" class="card-img-top" alt="{{ image.alternative }}">
                                        {% endfor %}
                                        <div class="card-body">
                                            <h3 class="card-title">{{ produit.nom | title }}</h3>
                                            <p class="card-text">{{ produit.description }}</p>
                                            <a class="card-link btn btn-primary " href="{{ path("app_product", {"categorie" : categorie.nom, "id" : produit.id} ) }}">En savoir plus...</a>
                                        </div>
                                        <div class="card-footer">
                                            <p class="card-text text-muted text-right"> Ajouté le : {{ produit.dateFr }} </p>
                                        </div>
                                    </div>
                                </div>
                            {% endif %}
                        {% endfor %}
                    </div>

                    {# Button to see a list of products for one categorie #}
                    <div class="row my-3">
                        <a class="btn btn-primary btn-lg col-8 mx-auto" href="{{ path("app_categorie", {"nom" : categorie.nom}) }}">Voir tout...</a>
                    </div>
                </div>

            {% endfor %}

            {# Separator #}
            <hr class="my-5">

        </div>
    </div>
{% endblock %}

templates/app/contact.html.twig
{% extends 'base.html.twig' %}

{#
    # Author : PORTET Marin
    # Description : This page is a contact form
#}

{% block title %}Contact {% endblock %}

{% block body %}
    <div class="pt-5">

        {# Main Title #}
        <div class="container">
            <h1 class="h1">Contact</h1>
        </div>

        <div class="container">
            <div class="form-group">
                {{ form_start(form) }}
                <div class="container">
                    <div class="row">
                        <div class="col-12">
                            <label for="contactForm-adresse">Adresse :</label>
                            {% if app.user %}
                                {{ form_widget(form.Adresse, { "attr" : {"id" : "contactForm-adresse", "class" : "form-control", "value" : app.user.email}}) }}
                            {% else %}
                                {{ form_widget(form.Adresse, { "attr" : {"id" : "contactForm-adresse", "class" : "form-control", "autofocus" : true}}) }}
                            {% endif %}
                        </div>

                        <div class="col-12">
                            <label for="contactForm-sujet">Sujet :</label>
                            {% if app.user %}
                                {{ form_widget(form.Sujet, { "attr" : {"id" : "contactForm-sujet", "class" : "form-control", "autofocus" : true}}) }}
                            {% else %}
                                {{ form_widget(form.Sujet, { "attr" : {"id" : "contactForm-sujet", "class" : "form-control"}}) }}
                            {% endif %}
                        </div>

                        <div class="col-12">
                            <label for="contactForm-message"> Message :</label>
                            {{ form_widget(form.Message, { "attr" : {"id" : "contactForm-message", "class" : "form-control", "rows" : 10, "cols" : 100}}) }}
                        </div>
                    </div>
                </div>

                <div class="row justify-content-center mt-4">
                    {{ form_widget(form.Envoyer, { "attr" : {"class" : "btn btn-primary btn-lg"} }) }}
                </div>

                {{ form_end(form) }}
            </div>
        </div>

        {# Separator #}
        <hr class="my-5">

    </div>
{% endblock %}

templates/app/index.html.twig
{% extends 'base.html.twig' %}

{#
    # Author : PORTET Marin
    # Description : This page is a home page.
#}

{% block title %}Home Page{% endblock %}

{% block body %}
    <div class="container-fluid">
        <div class="jumbotron jumbotron-fluid">
            <div class="container">
                <div class="row row-cols-1 row-cols-lg-2 align-items-center justify-content-center">
                    <div class="col">
                        {% if app.user %}
                            <h1 class="display-4">Bienvenue, {{ app.user.pseudo | capitalize }}, sur ShopNet !</h1>
                        {% else %}
                            <h1 class="display-4">Bienvenue sur ShopNet !</h1>
                        {% endif %}
                        <p class="lead">La date d'aujourd'hui est le {{ dateFr.semaine | title }} {{ dateFr | title }}.</p>
                    </div>
                    <div class="col">
                        <div class="d-flex flex-row flex-wrap justify-content-around">
                            <a href="{{ path("user_inscription") }}" class="btn btn-primary btn-lg">Nous rejoindre !</a>
                            <a href="{{ path("user_connexion") }}" class="btn btn-secondary btn-lg"> Déjà membre ?</a>
                        </div>
                    </div>
                </div>
            </div>

            {# Separator #}
            <hr class="my-1">
        </div>

        {# Separator #}
        <hr class="my-5">

        {# Carrousel #}
        <div class="container-fluid">
            <div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
                <ol class="carousel-indicators">
                    {% for i in 0..2 %}
                        {% if i == 0 %}
                            <li data-target="#carouselExampleIndicators" data-slide-to="{{ i }}" class="active"></li>
                        {% else %}
                            <li data-target="#carouselExampleIndicators" data-slide-to="{{ i }}"></li>
                        {% endif %}
                    {% endfor %}
                </ol>
                <div class="carousel-inner">
                    {% for i in 0..2 %}
                        {% if i == 0 %}
                            <div class="carousel-item active">
                                <img src="{{ asset("img/collection-summer.jpg") }}" class="d-block w-100" alt="...">
                                <div class="carousel-caption d-none d-md-block">
                                    <h5>First slide label</h5>
                                    <p>Nulla vitae elit libero, a pharetra augue mollis interdum.</p>
                                </div>
                            </div>
                        {% else %}
                            <div class="carousel-item">
                                <img src="{{ asset("img/collection-summer.jpg") }}" class="d-block w-100" alt="...">
                                <div class="carousel-caption d-none d-md-block ">
                                    <h5>First slide label</h5>
                                    <p>Nulla vitae elit libero, a pharetra augue mollis interdum.</p>
                                </div>
                            </div>
                        {% endif %}
                    {% endfor %}
                </div>
                <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="sr-only">Previous</span>
                </a>
                <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="sr-only">Next</span>
                </a>
            </div>
        </div>

        {# Separator #}
        <hr class="my-5">

        {# List of random products #}
        <div class="row row-cols-1 row-cols-md-2 row-cols-lg-3 row-cols-xl-4">
            {% for p in produits %}
                <div class="col mb-3">
                    <div class="card h-100">
                        {% for img in p.images %}
                            <img src="{{ img }}" class="card-img-top" alt="{{ img.alternative }}">
                        {% endfor %}
                        <div class="card-body ">
                            <h3 class="card-title"> {{ p.nom | capitalize }} </h3>
                            <p class="card-text"> {{ p.description }} </p>
                            <p class="card-text"> Prix : <span class="font-weight-bold">{{ p.prix }} €</span></p>
                            <a class="card-link btn btn-primary" href="{{ path("app_product", {"categorie" : p.categorie, "id" : p.id} ) }}">En savoir plus...</a>
                        </div>
                        <div class="card-footer">
                            <p class="card-text text-muted text-right"> Ajouté le : {{ p.dateFr }}</p>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>

        {# Separator #}
        <hr class="my-5">

    </div>
{% endblock %}
{% block javascripts %}
    <script src="{{ asset("js/vue/app.js") }}"></script>
{% endblock %}

templates/app/product.html.twig
{% extends 'base.html.twig' %}

{#
    # Author : PORTET Marin
    # Description : This page is a presentation of a product
#}

{% block title %}Produit {{ produit.id }}{% endblock %}

{% block body %}
    <div class="pt-5">

        {# Main Title #}
        <div class="container-fluid">
            <h1 class="h1 font-weight-bold">{{ produit.categorie | title }} - {{ produit.nom | title }}</h1>
        </div>

        {# Separator #}
        <hr class="my-5">

        {# Product Presentation #}
        <div class="container-fluid">
            <div class="row row-cols-1 row-cols-lg-2">
                {% for image in produit.images %}
                    <img src="{{ image.chemin }}" class="col" alt="{{ image.alternative }}">
                {% endfor %}
                <div class="container col">

                    <h5 class="h2">{{ produit.nom | capitalize}}</h5>
                    <p><span class="font-weight-bold">Description</span> : {{ produit.description }}</p>
                    <p><span class="font-weight-bold">Prix</span> : {{ produit.prix }} €</p>
                    <p><span class="font-weight-bold">Categorie</span> : {{ produit.categorie | capitalize}}</p>
                    <p><span class="font-weight-bold">En Stock</span> : {{ produit.quantite }}</p>
                    <p><span class="font-weight-bold">Date de sortie</span> : {{ produit.dateFr }}</p>

                    {# Separator #}
                    <hr class="my-1">

                    {% if app.user %}
                        {# Formulaire Personnalisation #}
                        <h5 class="h2">Personnalisation</h5>
                        <div class="form-group">
                            {{ form_start(formPanier) }}
                                <div class="row row-cols-1 row-cols-md-3 ">
                                    <label class="col" for="ajoutFormType-taille">
                                        {{ form_row(formPanier.tailles, {"attr" : {"id" : "ajoutFormType-taille", "class" : "custom-select"}}) }}
                                    </label>

                                    <label class="col" for="ajoutFormType-couleur">
                                        {{ form_row(formPanier.couleurs, {"attr" : {"id" : "ajoutFormType-couleur", "class" : "custom-select"}}) }}
                                    </label>

                                    <label class="col" for="ajoutFormType-nombre">
                                        {{ form_row(formPanier.quantite, { "attr" : {"id" : "ajoutFormType-nombre", "class" : "form-control", "value" : 1, "min" : 1, "max" : produit.quantite} }) }}
                                    </label>
                                </div>
                                {{ form_widget(formPanier.ajouter_au_panier, { "attr" : {"class" : "btn btn-primary"} }) }}
                            {{ form_end(formPanier) }}
                        </div>
                    {% else %}
                        <h5 class="h3 h3-responsive">Pour commander ce produit...</h5>
                        <div class="row row-cols-1 row-cols-md-2 align-content-center justify-content-center">
                            <div class="col-8 col-md-4 mt-2 mt-md-4 ">
                                <div class="row justify-content-center">
                                    <a href="{{ path("user_inscription") }}" class="btn btn-primary btn-lg">Nous rejoindre !</a>
                                </div>
                            </div>
                            <div class="col-8 col-md-4 mt-4 ">
                                <div class="row justify-content-center">
                                    <a href="{{ path("user_connexion") }}" class="btn btn-secondary btn-lg text-center"> Déjà membre ?</a>
                                </div>

                            </div>

                        </div>
                    {% endif %}

                </div>
            </div>
        </div>

        {# Separator #}
        <hr class="mt-5 mb-1">

        {# Tags Product #}
        <div class="col">
            <p><span class="font-weight-bold">Tags</span> :
                {% for key, tag in produit.tags %}
                    {% if key == produit.tags|length-1 %}
                        <a class="text-muted text-decoration-none" href="{{ path("tag_search", {"tag" : tag.nom}) }}">{{ tag.nom }}</a>
                    {% else %}
                        <a class="text-muted text-decoration-none" href="{{ path("tag_search", {"tag" : tag.nom}) }}">{{ tag.nom }}</a>,
                    {% endif %}
                {% endfor %}
            </p>
        </div>

        {# Separator #}
        <hr class="my-5">
        {% if app.user %}

            {# Formulaire Commentary #}
            <div id="formulaire-commentary" class="container">
                <h5 class="h2">Laissez nous votre avis sur ce produit :</h5>
                <div class="container form-group">
                    {{ form_start(formCommentaire) }}
                    <div class="row">

                        <label class="col" for="commentFormType-message">
                            {{ form_widget(formCommentaire.message, {"attr" : {"id" : "commentFormType-message", "class" : "form-control", "rows" : 10} }) }}
                        </label>

                    </div>
                    {{ form_widget(formCommentaire.donnez_votre_avis, { "attr" : {"class" : "btn btn-primary"} }) }}
                    {{ form_end(formCommentaire) }}
                </div>
            </div>
        {% else %}
            <div class="container">
                <h5 class="h3 h3-responsive">Pour nous laissez votre avis...</h5>
                <div class="row row-cols-1 row-cols-md-2 align-content-center justify-content-center">
                    <div class="col-8 col-md-3 mt-2 mt-md-4 ">
                        <div class="row justify-content-center">
                            <a href="{{ path("user_inscription") }}" class="btn btn-primary btn-lg">Nous rejoindre !</a>
                        </div>
                    </div>
                    <div class="col-8 col-md-3 mt-4 ">
                        <div class="row justify-content-center">
                            <a href="{{ path("user_connexion") }}" class="btn btn-secondary btn-lg text-center"> Déjà membre ?</a>
                        </div>

                    </div>

                </div>
            </div>

        {% endif %}


        {# Separator #}
        <hr class="my-5">

        {# Commentary #}
        <div id="section-commentaire" class="container">

            <h5 class="h2 mb-4">Avis des clients :</h5>
            {% if produit.commentaires|length == 0 %}
                <div class="container">
                    <p class="text-center">Il n'y a aucun avis sur ce produit.</p>
                </div>
            {% else %}

                <div class="row row-cols-1">
                    {% for commentaire in produit.commentaires|reverse %}
                        <div id="block-commentaire" class="col align-self-center">
                            <div class="container">

                                {# One commentary #}
                                <div class="row">
                                    <div class="container col">
                                        <div class="row row-cols-md-2 row-cols-1">
                                            <div class="col col-md-2 col-lg-1">
                                                <img class="rounded-circle " src="{{ asset(commentaire.user.image) }}" alt="" width="75" height="75">
                                            </div>
                                            <div class="col col-md-10 col-lg-10">
                                                <h6 class="h3 align-self-center">{{ commentaire.user.pseudo }}</h6>
                                                <p class="font-smaller text-muted">Posté le : {{ commentaire.dateFr }}</p>
                                            </div>
                                        </div>

                                        <div class="container col-9 border rounded bg-light ">
                                            <p> <span class="font-weight-bold">Avis : </span>{{ commentaire.message }}</p>
                                        </div>
                                        <div class="col-8">
                                            {% if app.user == commentaire.user %}
                                                <a href="{{ path("commentaire_delete", {"categorie" : produit.categorie, "id" : produit.id, "commentaire" : commentaire.id} ) }}"><i class="fi-x-circle"></i></a>
                                            {% endif %}
                                        </div>
                                    </div>
                                </div>

                                {# Separator #}
                                <hr class="my-4">
                            </div>
                        </div>
                    {% endfor %}
                </div>
            {% endif %}
        </div>

        {# Separator #}
        <hr class="my-5">


    </div>
{% endblock %}