src/Entity/User.php
<?php

namespace App\Entity;

use ApiPlatform\Core\Annotation\ApiResource;
use ApiPlatform\Core\Annotation\ApiFilter;
use ApiPlatform\Core\Bridge\Doctrine\Orm\Filter\SearchFilter;
use ApiPlatform\Core\Bridge\Doctrine\Orm\Filter\OrderFilter;
use ApiPlatform\Core\Bridge\Doctrine\Orm\Filter\RangeFilter;
use ApiPlatform\Core\Bridge\Doctrine\Orm\Filter\DateFilter;
use DateTime;
use DateTimeInterface;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints\Date;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Serializer\Annotation\Groups;

/**
 * Entité pour un utilisateur.
 * @ORM\Entity(repositoryClass="App\Repository\UserRepository")
 * @ApiResource(
 *     collectionOperations={
 *          "get"
 *      },
 *     itemOperations={
 *          "get",
 *          "patch"={"security"="is_granted('ROLE_USER')"}
 *      },
 *      normalizationContext={
 *          "groups"={"user"}
 *      }
 * )
 * @ApiFilter(SearchFilter::class, properties={
 *     "email": "exact",
 *     "nom": "exact",
 *     "prenom" : "exact",
 *     "pseudo" : "exact",
 *     "adresse" : "exact",
 *     "CB" : "exact",
 *     "commentaires" : "exact",
 *     "image" : "exact"
 * })
 * @ApiFilter(DateFilter::class, properties={"date"})
 * @ApiFilter(OrderFilter::class,
 *     properties={"id", "email", "nom", "prenom", "pseudo", "date"},
 *     arguments={"orderParameterName"="order"}
 *)
 */
class User implements UserInterface
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     * @Groups({"user", "commentaire", "commande"})
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     * @Assert\Email(
     *     message = "{{ value }} n'est pas une adresse mail valide."
     * )
     * @Groups({"user"})
     */
    private $email;

    /**
     * @ORM\Column(type="json")
     * @Groups({"user", "commentaire"})
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     * @Assert\Length(
     *     min=8,
     *     max=255,
     *     minMessage="Votre mot de passe doit faire une longueur de minumum {{ limit }} caractères.",
     *     maxMessage="La longueur maximal de {{ limit }} caractères est atteint."
     * )
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank
     * @Groups({"user", "commentaire"})
     */
    private $pseudo;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank
     * @Groups({"user"})
     */
    private $nom;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank
     * @Groups({"user"})
     */
    private $prenom;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Commentaire", mappedBy="user")
     * @Groups({"user"})
     */
    private $commentaires;

    /**
     * @ORM\OneToOne(targetEntity="App\Entity\Adresse", mappedBy="user")
     * @Groups({"user"})
     */
    private $adresse;

    /**
     * @ORM\OneToOne(targetEntity="App\Entity\Image", inversedBy="user", cascade={"persist", "remove"})
     * @Groups({"user"})
     */
    private $image;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Commande", mappedBy="user")
     * @Groups({"user"})
     */
    private $commandes;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\CB", mappedBy="user")
     * @Groups({"user"})
     */
    private $CB;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     * @Groups({"user"})
     */
    private $date;
    private $dateFr;

    public function __construct()
    {
        $this->date = new \DateTime();
        $this->commentaires = new ArrayCollection();
        $this->commandes = new ArrayCollection();
        $this->CB = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return (string) $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getSalt()
    {
        // not needed when using the "bcrypt" algorithm in security.yaml
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getPseudo(): ?string
    {
        return $this->pseudo;
    }

    public function setPseudo(string $pseudo): self
    {
        $this->pseudo = $pseudo;

        return $this;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): self
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function __toString()
    {
        // TODO: Implement __toString() method.
        return $this->nom . " " . $this->prenom;
    }

    /**
     * @return Collection|Commentaire[]
     */
    public function getCommentaires(): Collection
    {
        return $this->commentaires;
    }

    public function addCommentaire(Commentaire $commentaire): self
    {
        if (!$this->commentaires->contains($commentaire)) {
            $this->commentaires[] = $commentaire;
            $commentaire->setUser($this);
        }

        return $this;
    }

    public function removeCommentaire(Commentaire $commentaire): self
    {
        if ($this->commentaires->contains($commentaire)) {
            $this->commentaires->removeElement($commentaire);
            // set the owning side to null (unless already changed)
            if ($commentaire->getUser() === $this) {
                $commentaire->setUser(null);
            }
        }

        return $this;
    }

    public function getAdresse(): ?Adresse
    {
        return $this->adresse;
    }

    public function setAdresse(?Adresse $adresse): self
    {
        $this->adresse = $adresse;

        // set (or unset) the owning side of the relation if necessary
        $newUser = null === $adresse ? null : $this;
        if ($adresse->getUser() !== $newUser) {
            $adresse->setUser($newUser);
        }

        return $this;
    }

    public function getImage(): ?Image
    {
        return $this->image;
    }

    public function setImage(?Image $image): self
    {
        $this->image = $image;

        return $this;
    }

    /**
     * @return Collection|Commande[]
     */
    public function getCommandes(): Collection
    {
        return $this->commandes;
    }

    public function addCommande(Commande $commande): self
    {
        if (!$this->commandes->contains($commande)) {
            $this->commandes[] = $commande;
            $commande->setUser($this);
        }

        return $this;
    }

    public function removeCommande(Commande $commande): self
    {
        if ($this->commandes->contains($commande)) {
            $this->commandes->removeElement($commande);
            // set the owning side to null (unless already changed)
            if ($commande->getUser() === $this) {
                $commande->setUser(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|CB[]
     */
    public function getCB(): Collection
    {
        return $this->CB;
    }

    public function addCB(CB $cB): self
    {
        if (!$this->CB->contains($cB)) {
            $this->CB[] = $cB;
            $cB->setUser($this);
        }

        return $this;
    }

    public function removeCB(CB $cB): self
    {
        if ($this->CB->contains($cB)) {
            $this->CB->removeElement($cB);
            // set the owning side to null (unless already changed)
            if ($cB->getUser() === $this) {
                $cB->setUser(null);
            }
        }

        return $this;
    }

    public function getDate(): ?\DateTime
    {
        return $this->date;
    }

    public function setDate(?\DateTime $date): self
    {
        $this->date = $date;

        return $this;
    }

    public function getDateFr()
    {
        $this->dateFr = new DateFr($this->date);
        return $this->dateFr;
    }


}

src/Controller/User/AdresseController.php
<?php

namespace App\Controller\User;

use App\Entity\Adresse;
use App\Entity\Categorie;
use App\Form\AdresseType;
use Doctrine\ORM\EntityManager;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * Controller qui gère l'adresse du profile.
 * Class AdresseController
 * @package App\Controller\User
 */
class AdresseController extends AbstractController
{
    /**
     * Modifier l'adresse.
     * @Route("/profil/adresse/modification", name="user_adresse_edit")
     * @param Request $request
     * @return Response
     */
    public function edit(Request $request)
    {

        $categories = $this->getDoctrine()->getRepository(Categorie::class)->findAll();
        $user = $this->getUser();

        $adresse =  $user->getAdresse();

        if( $adresse === NULL){
            $adresse = new Adresse();
        }

        $form = $this->createForm(AdresseType::class, $adresse);
        $form->handleRequest($request);
        if( $form->isSubmitted() && $form->isValid() ){

            $manager = $this->getDoctrine()->getManager();

            $user->setAdresse($adresse);

            $manager->persist($adresse);

            $manager->flush();

            return $this->redirectToRoute("user_profil", ["pseudo" => $user->getPseudo()]);
        }

        return $this->render('user/adresse/edit.html.twig', [
            "categories" => $categories,
            "form" => $form->createView()
        ]);
    }

    /**
     * Supprimer l'adresse.
     * @Route("/profil/adresse/supprimer", name="user_adresse_delete")
     * @return Response
     */
    public function delete()
    {
        $manager = $this->getDoctrine()->getManager();
        $user = $this->getUser();
        $adresse = $user->getAdresse();

        $manager->remove($adresse);
        $manager->flush();

        return $this->redirectToRoute("user_profil", ["pseudo" => $user->getPseudo()] );
    }
}

src/Controller/User/CBController.php
<?php

namespace App\Controller\User;

use App\Entity\Categorie;
use App\Entity\CB;
use App\Form\CBType;
use App\Repository\CategorieRepository;
use DateTime;
use DateTimeZone;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * Controller qui gère les informations de paiement du profile.
 * Class CBController
 * @package App\Controller\User
 */
class CBController extends AbstractController
{
    /**
     * Ajouter une carte bancaire.
     * @Route("/CB/ajouter", name="user_cb_add")
     * @param Request $request
     * @param EntityManagerInterface $manager
     * @param CategorieRepository $doctrineCategorie
     * @return Response
     * @throws \Exception
     */
    public function add(Request $request, EntityManagerInterface $manager ,CategorieRepository $doctrineCategorie)
    {
        $categories = $doctrineCategorie->findAll();
        $user = $this->getUser();
        $cb = new CB();
        $form = $this->createForm(CBType::class, $cb);
        $form->handleRequest($request);

        if( $form->isSubmitted() && $form->isValid() ) {

            /** Doc PHP :
             * PASSWORD_DEFAULT : Cette constante est concue pour changer dans le temps, au fur et à mesure que
             * des algorithmes plus récents et plus forts sont ajoutés à PHP.
            */
            //DateTime::createFromFormat( "d/m/y H:i", "01/" . $form->get("date")->getData() . " 23:59" )

            $cb->setNumero( password_hash($form->get("numero")->getData(), PASSWORD_DEFAULT ) );
            $cb->setCryptogramme( password_hash($form->get("cryptogramme")->getData(), PASSWORD_DEFAULT ) );
            $cb->setDate( $form->get("date")->getData() );
            $cb->setTitulaire( $form->get("titulaire")->getData() );
            $cb->setUser($user);

            $manager->persist($cb);
            $manager->flush();

            return $this->redirectToRoute("user_profil", ["pseudo" => $user->getPseudo()]);
        }

        return $this->render('user/cb/add.html.twig', [
            'categories' => $categories,
            "form" => $form->createView()
        ]);
    }

    /**
     * Supprimer une carte bancaire
     * @Route("/CB/supprimer/{id}", name="user_cb_delete")
     * @param $id
     * @param EntityManagerInterface $manager
     * @return Response
     */
    public function delete($id, EntityManagerInterface $manager )
    {
        $user = $this->getUser();
        $cb = $this->getDoctrine()->getRepository(CB::class)->find($id);

        $manager->remove($cb);
        $manager->flush();

        return $this->redirectToRoute("user_profil", ["pseudo" => $user->getPseudo()]);
    }
}

templates/user/connexion.html.twig
{% extends 'base.html.twig' %}

{% block title %}Connexion{% endblock %}

{% block body %}
    <div class="pt-5">
        <form method="post">
            {% if error %}
                <div class="alert alert-danger">{{ error.messageKey|trans(error.messageData, 'security') }}</div>
            {% endif %}

            {% if app.user %}
                <div class="mb-3">
                    You are logged in as {{ app.user.username }}, <a href="{{ path('user_deconnexion') }}">Logout</a>
                </div>
            {% endif %}

            <div class="container">

                <h1 class="h1">Connexion</h1>

                <div class="container">
                    <label for="inputEmail">Email</label>
                    <input type="email" value="{{ last_username }}" name="email" id="inputEmail" class="form-control" required autofocus>
                    <label for="inputPassword">Mot de passe</label>
                    <input type="password" name="password" id="inputPassword" class="form-control" required>

                    <input type="hidden" name="_csrf_token"
                           value="{{ csrf_token('authenticate') }}"
                    >

                    <div class="row justify-content-center my-3">
                        <button class="btn btn-lg btn-primary" type="submit">
                            Connexion
                        </button>
                    </div>

                </div>

            </div>

        </form>

        {# Separator #}
        <hr class="my-5">

    </div>
{% endblock %}

templates/user/inscription.html.twig
{% extends 'base.html.twig' %}

{#
    # Author : PORTET Marin
    # Description : This page is for sign up
#}

{% block title %}Inscription{% endblock %}

{% block body %}
    <div class="pt-5">

        {# Main Title #}
        <div class="container">
            <h1 class="h1">Inscription</h1>
        </div>

        {# Sign up form#}
        <div class="container">
            <div class="form-group">

                {{ form_start(form) }}
                <div class=" container row row-cols-1">

                    <div class="col">
                        {{ form_row(form.nom,{ "attr" : {"id" : "form-nom", "class" : "form-control", "autofocus" : true } }) }}
                    </div>

                    <div class="col">
                        {{ form_row(form.prenom, { "attr" : {"id" : "form-prenom", "class" : "form-control" }}) }}
                    </div>

                    <div class="col">
                        {{ form_row(form.pseudo,{ "attr" : {"id" : "form-pseudo", "class" : "form-control" }}) }}
                    </div>

                    <div class="col">
                        {{ form_row(form.email,{ "attr" : {"id" : "form-email", "class" : "form-control" }}) }}
                    </div>

                    <div class="col">
                        {{ form_row(form.password,{ "attr" : {"id" : "form-password", "class" : "form-control" }}) }}
                    </div>

                </div>

                <div class="row justify-content-center mt-4">
                    {{ form_widget(form.confirmer,{ "attr" : {"class" : "btn btn-primary btn-lg"}}) }}
                </div>


                {{ form_end(form) }}

            </div>
        </div>

        {# Separator #}
        <hr class="my-5">

    </div>
{% endblock %}

templates/user/panier.html.twig
{% extends 'base.html.twig' %}

{#
    # Author : PORTET Marin
    # Description : This page is for cart
#}

{% block title %}Panier{% endblock %}

{% block body %}
    <div class="pt-5">
        <div class="container-fluid">


            {# Main Title #}
            <div class="container">
                <h1 class="h1">Panier de {{ app.user.pseudo }} </h1>
            </div>


            {# Separator #}
            <div class="my-5"></div>

            <div class="container">
                <div class="row row-cols-1 border rounded justify-content-center align-items-center">
                    <div class="col bg-primary mb-3">
                        <div class="row row-cols-2 border-bottom justify-content-between align-items-center">
                            <div class="col">
                                <h2 class="h3 text-white">Articles</h2>
                            </div>
                        </div>
                    </div>

                    <div class="col border-bottom pb-3">
                        {% if panier|length == 0 %}
                            <p class="text-body">Vous n'avez aucun produit dans votre panier</p>
                        {% else %}
                            <div class="table-responsive">
                                <table class="table border">
                                    <thead class="thead-dark">
                                    <tr>
                                        <th scope="col">Produit</th>
                                        <th scope="col">Taille</th>
                                        <th scope="col">Couleur</th>
                                        <th scope="col">Prix(€)</th>
                                        <th scope="col">Quantité</th>
                                        <th scope="col">Supprimer</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    {% for index, item in panier %}
                                        <tr>
                                            <th scope="row"><a href="{{ path("app_product", {"categorie" : item.produit.categorie.nom, "id" : item.produit.id} ) }}">{{ item.produit.nom }}</a></th>
                                            <td>{{ item.taille }}</td>
                                            <td>{{ item.couleur }}</td>
                                            <td>{{ item.produit.prix }}€</td>
                                            <td>{{ item.nombre }}</td>
                                            <td><a href="{{ path("panier_delete", {"index" : index} ) }}">Supprimer</a></td>
                                        </tr>
                                    {% endfor %}
                                    </tbody>
                                </table>
                            </div>

                            {% set prixTotal = 0 %}
                            {% for item in panier %}
                                {% set prixTotal = prixTotal + ( item.produit.prix * item.nombre) %}
                            {% endfor %}
                            <p>Nombre d'articles : <span class="font-weight-bold">{{ panier|length }}</span></p>
                            <p>Prix Total : <span class="font-weight-bold">{{ prixTotal }}€</span></p>
                        {% endif %}
                    </div>
                </div>
            </div>

            {# Separator #}
            <div class="my-5"></div>

            {% if panier|length != 0 %}
            <div class="container">
                <div class="row  justify-content-end ">
                    <a class="col-5 col-md-3 col-lg-2 mr-5 btn btn-primary btn-lg" href="{{ path("commande_adresse") }}">Commander</a>
                </div>
            </div>
            {% endif %}


            {# Separator #}
            <div class="my-5"></div>


        </div>
    </div>
{% endblock %}